#include "identification/data_loader.hpp"
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>

ExperimentData DataLoader::loadCSV(const std::string &filename,
                                   std::size_t n_dof) {
  ExperimentData data;
  std::ifstream file(filename);

  if (!file.is_open()) {
    throw std::runtime_error("Could not open file: " + filename);
  }

  std::string line;
  // Skip header
  std::getline(file, line);

  std::vector<double> time_vec;
  std::vector<std::vector<double>> q_vec, qd_vec, tau_vec;

  while (std::getline(file, line)) {
    std::stringstream ss(line);
    std::string token;
    std::vector<double> row;

    while (std::getline(ss, token, ',')) {
      row.push_back(std::stod(token));
    }

    // Expected columns: time(1) + q(n_dof) + qd(n_dof) + tau(n_dof)
    // Note: The CSV generated by force_node has: time, q1..q7, qd1..qd7,
    // tau1..tau7 Total columns = 1 + 3 * n_dof But force_node uses
    // NUM_ARM_JOINTS which is 7. Let's verify column count.

    if (row.size() < 1 + 3 * n_dof) {
      continue; // Skip invalid lines
    }

    time_vec.push_back(row[0]);

    std::vector<double> q_row, qd_row, tau_row;
    for (std::size_t i = 0; i < n_dof; ++i)
      q_row.push_back(row[1 + i]);
    for (std::size_t i = 0; i < n_dof; ++i)
      qd_row.push_back(row[1 + n_dof + i]);
    for (std::size_t i = 0; i < n_dof; ++i)
      tau_row.push_back(row[1 + 2 * n_dof + i]);

    q_vec.push_back(q_row);
    qd_vec.push_back(qd_row);
    tau_vec.push_back(tau_row);
  }

  data.n_samples = time_vec.size();
  data.n_dof = n_dof;
  data.time = time_vec;

  data.q.resize(data.n_samples, n_dof);
  data.qd.resize(data.n_samples, n_dof);
  data.tau.resize(data.n_samples, n_dof);

  for (std::size_t i = 0; i < data.n_samples; ++i) {
    for (std::size_t j = 0; j < n_dof; ++j) {
      data.q(i, j) = q_vec[i][j];
      data.qd(i, j) = qd_vec[i][j];
      data.tau(i, j) = tau_vec[i][j];
    }
  }

  std::cout << "Loaded " << data.n_samples << " samples from " << filename
            << std::endl;
  return data;
}
